### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by S-Ha** [Takumon/asciidoc-syntax-quick-reference-japanese-translation#2]
9.2と19.2で「インライン要素」が「インラン要素」になってます。

**Comment by faithandbrave** [comment]
#3 で修正済みです。

**Comment by Takumon** [comment]
S-HaさんIssueをあげてくださってありがとうございます。
faithandbraveさん修正プルリクありがとうございます。
本件はプルリクをマスタに取り込んだのでクローズとさせていただきます。
